import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

const TermsPage: React.FC = () => {
  const navigate = useNavigate();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <article className="min-h-screen bg-white">
      {/* Hero Header */}
      <div className="relative w-full py-16 px-6 bg-cyan-400 border-b-8 border-black overflow-hidden">
        <div className="absolute inset-0 bg-halftone opacity-20"></div>
        <div className="max-w-4xl mx-auto relative z-10 text-center">
          <h1 className="text-5xl md:text-7xl font-['Bangers'] text-white text-shadow-pop" style={{ WebkitTextStroke: '2px black' }}>
            TERMS OF ART
          </h1>
          <p className="mt-4 text-xl font-bold bg-black text-white inline-block px-3 py-1">
            Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-6 py-16">
        <div className="prose prose-xl text-black max-w-none space-y-8">

          <section>
            <h2 className="text-3xl font-['Bangers'] text-pink-500 mb-4" style={{ WebkitTextStroke: '1px black' }}>1. ACCEPTANCE OF TERMS</h2>
            <p className="font-bold leading-relaxed">
              By accessing and using Popunch ("the Service"), you accept and agree to be bound by these Terms of Art. If you do not agree to these terms, please do not use our Service. These terms apply to all visitors, users, and others who access or use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-['Bangers'] text-pink-500 mb-4" style={{ WebkitTextStroke: '1px black' }}>2. USE OF SERVICE</h2>
            <p className="font-bold leading-relaxed">
              Popunch provides an AI-powered comic creation tool. You may use this Service for personal, non-commercial purposes. You agree not to misuse the Service or help anyone else do so. You must not use the Service to create content that is illegal, harmful, threatening, abusive, or otherwise objectionable.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-['Bangers'] text-pink-500 mb-4" style={{ WebkitTextStroke: '1px black' }}>3. USER CONTENT</h2>
            <p className="font-bold leading-relaxed">
              You retain ownership of any content you submit, post, or display on or through the Service. By submitting content, you grant Popunch a worldwide, non-exclusive, royalty-free license to use, reproduce, and display such content solely for the purpose of operating and providing the Service.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-['Bangers'] text-pink-500 mb-4" style={{ WebkitTextStroke: '1px black' }}>4. AI-GENERATED CONTENT</h2>
            <p className="font-bold leading-relaxed">
              Content generated by our AI tools is provided "as is" without warranties of any kind. You are responsible for reviewing and editing AI-generated content before use. Popunch does not guarantee the accuracy, completeness, or appropriateness of AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-['Bangers'] text-pink-500 mb-4" style={{ WebkitTextStroke: '1px black' }}>5. INTELLECTUAL PROPERTY</h2>
            <p className="font-bold leading-relaxed">
              The Service and its original content, features, and functionality are owned by Pixdyne and are protected by international copyright, trademark, and other intellectual property laws. Our pop art styling, Ben-Day patterns, and unique visual elements are part of our brand identity.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-['Bangers'] text-pink-500 mb-4" style={{ WebkitTextStroke: '1px black' }}>6. LIMITATION OF LIABILITY</h2>
            <p className="font-bold leading-relaxed">
              In no event shall Popunch, Pixdyne, or its directors, employees, or agents be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-['Bangers'] text-pink-500 mb-4" style={{ WebkitTextStroke: '1px black' }}>7. CHANGES TO TERMS</h2>
            <p className="font-bold leading-relaxed">
              We reserve the right to modify or replace these terms at any time. We will provide notice of any changes by posting the new terms on this page. Your continued use of the Service after any changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-['Bangers'] text-pink-500 mb-4" style={{ WebkitTextStroke: '1px black' }}>8. CONTACT</h2>
            <p className="font-bold leading-relaxed">
              If you have any questions about these Terms, please contact us at <a href="https://pixdyne.com" target="_blank" rel="noreferrer" className="text-cyan-500 hover:underline">pixdyne.com</a>.
            </p>
          </section>

        </div>

        {/* Navigation Footer */}
        <div className="mt-16 border-t-4 border-black border-dashed pt-8">
          <button
            onClick={() => navigate('/')}
            className="flex items-center gap-2 font-bold hover:text-cyan-600 transition-colors"
          >
            ← BACK TO HOME
          </button>
        </div>
      </div>
    </article>
  );
};

export default TermsPage;
